import * as React from 'react';
import { SvgCss } from 'react-native-svg';

interface Props {
  width?: number;
  height?: number;
  color?: string;
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="512px" height="512px" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
 <!-- Generated by Pixelmator Pro 1.5.4 -->
 <g id="group">
  <g id="group-1">
   <path id="Path" d="M137.824 401.614 L241.824 506.118 C241.83 506.124 241.837 506.129 241.843 506.136 249.661 513.968 262.365 513.943 270.157 506.134 270.163 506.128 270.17 506.123 270.176 506.116 L374.176 401.612 C381.967 393.783 381.938 381.119 374.108 373.327 366.279 365.535 353.616 365.565 345.824 373.394 L276 443.558 276 20 C276 8.954 267.046 0 256 0 244.954 0 236 8.954 236 20 L236 443.558 166.176 373.396 C158.384 365.567 145.721 365.537 137.892 373.329 130.061 381.122 130.034 393.786 137.824 401.614 Z"  fill-opacity="1" stroke="none"/>
  </g>
 </g>
 <g id="group-2"/>
 <g id="group-3"/>
 <g id="group-4"/>
 <g id="group-5"/>
 <g id="group-6"/>
 <g id="group-7"/>
 <g id="group-8"/>
 <g id="group-9"/>
 <g id="group-10"/>
 <g id="group-11"/>
 <g id="group-12"/>
 <g id="group-13"/>
 <g id="group-14"/>
 <g id="group-15"/>
 <g id="group-16"/>
</svg>`;

const BDownIcon: React.FC<Props> = ({ width, height, color }) => {
  return <SvgCss xml={xml} width={width} height={height} fill={color} />;
};
export { BDownIcon };
